name: Build Liferay Workspace

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Workspace
        uses: lgdd/liferay-build-action@v1
        with:
          workspace-directory: ./liferay-workspace
          java-version: '17'
          profile: 'prod'
          upload-bundle: true
          upload-artifacts: true
          retention-days: '1'
      - name: Download Built Artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
      - name: Verify Artifacts
        run: ls -la