name: Build Liferay Workspace

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Workspace
        uses: lgdd/liferay-build-action@v2
        with:
          workspace-directory: ./liferay-workspace
          java-version: '17'
          build-extra-args: '-x :modules:ai-tasks-rest-test:build'
          profile: 'prod'
          upload-bundle: true
          upload-artifacts: true
          retention-days: '1'
      - name: Download Built Artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts--jdk-17
      - name: Verify Artifacts
        run: ls -la
      - name: Download Built Bundle
        uses: actions/download-artifact@v4
        with:
          name: bundle--jdk-17
      - name: Verify Bundle
        run: ls -la