name: Frontend Formatting

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Format AI Tasks Admin Web
        working-directory: ./liferay-workspace/client-extensions/ai-tasks-admin-web
        run: npm run format
      - name: Format AI Tasks Chat
        working-directory: ./liferay-workspace/client-extensions/ai-tasks-chat
        run: npm run format
      - name: Commit Format Changes
        working-directory: ./liferay-workspace/client-extensions
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add *.js *.jsx *.ts *.tsx *.json *.css *.scss *.md
          git commit -am "chore: auto format frontends" || echo "We're good for now. See you next time!"
          git pull --rebase
          git push
